name: Fake Test

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  fake-test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Fake Tests
      run: bash -c "sleep 1; echo done!"
